// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


var vPow = Math.pow(20.0, 0.16);

var windChill = 13.12 + 0.6215 * 5.0 - 11.37 * vPow + 0.3965 * 5.0 * vPow;

console.log("At temperature " + (String(5.0) + (" degrees Celsius and wind speed " + (String(20.0) + (" km/hr, the wind chill temperature is " + (String(windChill) + " degrees Celsius. "))))));

var t = 5.0;

var v = 20.0;

exports.t = t;
exports.v = v;
exports.vPow = vPow;
exports.windChill = windChill;
/* vPow Not a pure module */
